tsudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: '2.7'

    - stage: deploy
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - docker image ls $DOCKER_IMAGE
        - docker run --rm -v `pwd`:/foo $DOCKER_IMAGE /foo/build-wheels.sh

cache:
  pip: true

addons:
  apt:
    packages:
      - python-dev


stage: test

install:
  - echo nothing to do
