tsudo: false
language: python
sudo: required

services:
  - docker
env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
install:
  - docker pull $DOCKER_IMAGE
script:
  - docker image ls $DOCKER_IMAGE
  - docker run --rm -v `pwd`:/foo $DOCKER_IMAGE /foo/build-wheels.sh
