language: python

jobs:
  include:
    - script: echo "pypy2.7 -m pip install $PKG"

  include:
    - script: echo "pypy3.5 -m pip install $PKG"


env:
  - PKG="numpy"
  - PKG="scipy"
  - PKG="cython"

