language: python

env:
  - PYPY="2.7" PKG="numpy"
  - PYPY="3.5" PKG="numpy"
  - PYPY="2.7" PKG="scipy"
  - PYPY="3.5" PKG="scipy"
  
script:
  - echo "hello world"
  - echo "PYPY = $PYPY"
  - echo "pip install $PKG"
